---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: nginx.cfg
        dest: /etc/nginx/nginx.cfg
      become: yes
    - name: copy default configuration file
      copy:
        src: default
        dest: /etc/nginx/default
      become: yes
    - name: copy the static web site
      copy:
        src: html/
        dest: /usr/share/nginx/html/
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
