---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
#    - name: copy the nginx config file and restart nginx
#      copy:
#        src: nginx.cfg
#        dest: /etc/nginx/nginx.cfg
#      become: yes
#    - name: copy default configuration file
#      copy:
#        src: default
#        dest: /etc/nginx/default
#      become: yes

    - name: copy the static web site
      copy:
        src: html/
        dest: /usr/share/nginx/html/
      become: yes

    # check only the page if working or not
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://www.example.com
   # more smart check the page if working or not and the page content also   
    - name: Check that a page returns a status 200 and fail if the word ghanem is not in the page contents
      uri:
        url: http://54.162.215.188  # type here your loadbalancer dns or "http://www.example.com" or "ip-address of the machine"
        return_content: yes
      register: this
      failed_when: "'ghanem' not in this.content"
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

  handlers:
    - name: start nginx
      service: name=nginx state=started
      
